version: '3.4'

services:
  frs-admin:
    build:
      dockerfile: Dockerfile
      context: .
      target: frs_crud
    container_name: "frs-admin"
    ports:
      - "8081:8080"
      - "5006:5005"
    environment:
      - POSTGRES_PASSWORD=h9Zn784HdT
      - POSTGRES_URL=jdbc:postgresql://hrkv042.kh.exadel.ua:5432/frs
    depends_on:
      - frs-api

  frs-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: frs_core
    container_name: "frs-api"
    ports:
      - "8082:8080"
      - "5005:5005"
    environment:
      - POSTGRES_PASSWORD=h9Zn784HdT
      - POSTGRES_URL=jdbc:postgresql://hrkv042.kh.exadel.ua:5432/frs
      - MONGO_URL=mongodb://hrkv042.kh.exadel.ua:27017


  frs-fe:
    build:
      context: ui
      dockerfile: docker-prod/Dockerfile
    container_name: "frs-ui"
    ports:
      - "8000:80"
    depends_on:
      - frs-api
      - frs-admin

  frs-core:
    container_name: "frs-core"
    build:
      context: embedding-calculator
    environment:
      - MONGODB_URI=mongodb://hrkv042.kh.exadel.ua:27017/efrs_db
      - ML_PORT=3000

