version: '3'
services:
  ml:
    container_name: ml
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    #mem_reservation: 6g
    #mem_limit: 6g
  mongo:
    container_name: mongo
    image: "mongo:4.0.4-xenial"
    ports:
      - "27117:27017"
    volumes:
      - ./mongo_data:/data
