version: '3'
services:
  e2e:
    container_name: e2e${ID:-}
    build: ./e2e
    environment:
      - ML_URL=http://ml${ID:-}:3000
      - MONGO_HOST=mongo${ID:-}
      - MONGO_PORT=27017
      - MONGO_DBNAME=efrs_tmp_db
    depends_on:
      - ml
  ml:
    container_name: ml${ID:-}
    build:
      context: ./ml
      args:
        - DO_RUN_TESTS=${DO_RUN_TESTS:-false}
    ports:
      - ${ML_PORT:-3000}:3000
    environment:
      - MONGO_HOST=mongo${ID:-}
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME:-}
    depends_on:
      - mongo
  mongo:
    container_name: mongo${ID}
    image: "mongo:4.0.4-xenial"
    ports:
      - ${MONGO_PORT:-27117}:27017
    volumes:
      - ./tmp/mongo_data:/data
