version: '3.4'

volumes:
  postgres-data:

services:
  frs-postgres-db:
    image: postgres:11.5
    container_name: "frs-postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=frs
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frs-admin:
    image: ${registry}frs-admin
    build:
      dockerfile: Dockerfile
      context: .
      target: frs_crud
    container_name: "frs-admin"
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/frs
    depends_on:
      - frs-postgres-db
      - frs-api

  frs-api:
    image: ${registry}frs-api
    build:
      dockerfile: Dockerfile
      context: .
      target: frs_core
    container_name: "frs-api"
    depends_on:
      - frs-postgres-db
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/frs

  frs-fe:
    image: ${registry}frs-fe
    build:
      context: ui
      dockerfile: docker-prod/Dockerfile
    container_name: "frs-ui"
    ports:
      - "8000:80"
    depends_on:
      - frs-api
      - frs-admin

  frs-core:
    image: ${registry}frs-core
    container_name: "frs-core"
    build:
      context: embedding-calculator
    environment:
      - ML_PORT=3000
