version: '3'
services:
  e2e:
    container_name: e2e
    build: ./e2e
    depends_on:
      - ml
  ml:
    container_name: ml
    build:
      context: ./ml
      args:
        - DO_RUN_TESTS=${DO_RUN_TESTS:-false}
    ports:
      - ${PORT:-3000}:3000
