version: '2.4'
services:
  e2e:
    container_name: ${COMPOSE_PROJECT_NAME:-frs-core}_e2e
    build: ./e2e
    environment:
      - ML_URL=http://ml:3000
      - API_KEY=${API_KEY:-}
      - DROP_DB=${DROP_DB:-}
      - MONGODB_URI=${MONGODB_URI:-}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=efrs_tmp_db
    depends_on:
      - ml
  ml:
    container_name: ${COMPOSE_PROJECT_NAME:-frs-core}_ml
    build:
      context: ./ml
      args:
        - SKIP_TESTS=${SKIP_TESTS:-}
    ports:
      - ${ML_PORT:-3000}:3000
    environment:
      - MONGODB_URI=${MONGODB_URI:-}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=${MONGODB_DBNAME:-}
      - SCANNER=${SCANNER:-}
      - IMG_LENGTH_LIMIT=${IMG_LENGTH_LIMIT:-}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-}
      - ML_PORT=${ML_PORT:-3000}
      - FORCE_FAIL_E2E_TESTS=${FORCE_FAIL_E2E_TESTS:-}
    mem_limit: ${MEM_LIMIT:-0}
    memswap_limit: ${MEM_LIMIT:-0}
    depends_on:
      - mongodb
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME:-frs-core}_mongodb
    image: "mongo:4.0.4-xenial"
    ports:
      - ${MONGODB_PORT:-27117}:27017
    volumes:
      - ./tmp/mongo_data:/data
