version: '2'
services:
  nginx:
    container_name: nginx
    image: "nginx:1.17.4"
    ports:
      - "5001:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ml
  ml:
    container_name: ml
    build: .
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: "mongo:4.0.4-xenial"
    ports:
      - "27117:27017"
    volumes:
      - ./mongo_data:/data
