version: '3.4'

services:
  compreface-fe:
    build:
      context: ../ui
      dockerfile: docker-dev/Dockerfile
    environment:
      - CLIENT_MAX_BODY_SIZE=${max_request_size}
      - PROXY_READ_TIMEOUT=${read_timeout}ms
      - PROXY_CONNECT_TIMEOUT=${connection_timeout}ms
