server:
  port: ${CRUD_PORT:8080}

spring:
#  jackson:
#    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/frs}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true # fix for Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        format_sql: true
    hibernate:
      ddl-auto: none
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: false

security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  expire-length: 86400000

proxy:
  baseUrl: ${PROXY_URL:http://localhost:5000}

swagger:
  auth:
    server: http://localhost:${server.port}
  info:
    title: Face Recognition Service - Client
    version: 0.0.2-SNAPSHOT