swagger: '2.0'
info:
  version: v1
  title: 'Python Core Service — frs-core'
  description: 'This is a component of Exadel Face Recognition Service. EFRS is a service for face recognition: upload images with faces of known people, then upload a new image, and the service will recognize faces in it.'
tags:
  - name: 'Core'
schemes:
  - http
definitions:
  ErrorResponseBody:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Service returns a message along with 4xx and 5xx error responses"
externalDocs:
  description: 'EFRS Confluence Space'
  url: 'https://confluence.exadel.com/display/EFRS'
