swagger: '2.0'
info:
  description: 'Exadel Face Recognition Service. EFRS Core microservice.'
  version: 0.1-snapshot
  title: 'EFRS Core'
tags:
  - name: 'EFRS Core'
schemes:
  - http
components:
  responses:
    BadRequestResponse:
      description: 'Bad request is provided'
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Detailed information about the error'
    InternalServerErrorResponse:
      description: 'Internal error has occurred'
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Detailed information about the error'
externalDocs:
  description: 'More documentation is available in Confluence'
  url: 'https://confluence.exadel.com/display/KC/Exadel+Face+Recognition+Service'
