swagger: '2.0'
info:
  description: 'Service for face recognition. Upload images with faces of known people, then upload a new image, and the service will recognize faces in it. All operations are applied only for faces associated with the specified API key. Recognition is not performed if the model is trained on only one face.'
  version: 0.1-snapshot
  title: 'Exadel Face Recognition Service'
tags:
  - name: 'Face Database'
  - name: 'Face Recognition ML Model'
  - name: 'Maintenance'
schemes:
  - http
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-Api-Key
components:
  parameters:
    RetrainParameter:
      name: retrain
      in: query
      description: 'Specify whether the model should start retraining immediately after the request is completed (set this parameter to value "no", if operating with a lot of images one after another). Allowed values: "yes", "no", "force". "Force" option will abort already running processes of classifier training.'
      required: 'false'
      type: string
      default: 'force'
    FaceNameParameter:
      name: face_name
      in: path
      description: 'Person''s name to whom the face belongs to.'
      required: 'false'
      type: string
    DetProbThresholdParameter:
      name: det_prob_threshold
      in: path
      description: 'The minimal percent confidence that found face is actually a face.'
      required: 'false'
      type: float
  responses:
    BadRequestResponse:
      description: 'Bad request is provided'
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Detailed information about the error'
    ClassifierIsAlreadyTrainingErrorResponse:
      description: 'Classifier is already training. Use parameters to force start training.'
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Detailed information about the error'
    InternalServerErrorResponse:
      description: 'Internal error has occurred'
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Detailed information about the error'
externalDocs:
  description: 'More documentation is available in Confluence'
  url: 'https://confluence.exadel.com/display/KC/Exadel+Face+Recognition+Service'
