name: Build and Push DEV CompreFace version

on: 
  push:
    branches:
      - master
      - 1.1.x

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3

    - name: Set outputs from git
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')"
        if [ "${{ github.ref_name }}" = "master" ]; then
          echo "::set-output name=env_name::dev"
        elif [ "${{ github.ref_name }}" = "1.1.x" ]; then
          echo "::set-output name=env_name::stage"
        else
          echo "::set-output name=env_name::Features"
        fi         

    - name: Check outputs
      run: |
        echo "Branch     : ${{ github.ref_name }}"
        echo "SHA        : ${{ steps.vars.outputs.sha_short }}"
        echo "Environment: ${{ steps.vars.outputs.env_name }}"

    - name: Build images
      env:
        VERSION: ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
        REGISTRY_PATH: ${{ env.REGISTRY }}/exadel-inc/compreface/
        APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
      working-directory: ./dev/
      run: |
        sed -i 's|registry=|registry=${REGISTRY_PATH}|g' .env
        sed -i 's/latest/${VERSION}/g' .env
        docker-compose build --build-arg APPERY_API_KEY=${APPERY_API_KEY}
        docker images

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push images to the Container registry
      working-directory: ./dev/
      run: |
        docker-compose push
