name: Build and Push DEV CompreFace version

on: 
  push:
    branches:
      - master
      - 1.1.x

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3

    - name: Set outputs from git
      id: vars
      run: |
        echo "SHA_SHORT=$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_ENV
        if [ "${{ github.ref_name }}" = "master" ]; then
          echo "ENV_NAME=dev" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" = "1.1.x" ]; then
          echo "ENV_NAME=stage" >> $GITHUB_ENV
        else
          echo "ENV_NAME=Features" >> $GITHUB_ENV
        fi         

    - name: Check outputs
      run: |
        echo "Branch     : ${{ github.ref_name }}"
        echo "SHA        : ${{ env.SHA_SHORT }}"
        echo "Environment: ${{ env.ENV_NAME }}"

    - name: Build images
      env:
        VERSION: ${{ github.ref_name }}-${{ env.SHA_SHORT }}
        REGISTRY_PATH: ${{ env.REGISTRY }}/exadel-inc/compreface/
        APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
      working-directory: ./dev/
      run: |
        echo "REGISTRY_PATH: $REGISTRY_PATH"
        echo "VERSION: $VERSION"
        sed -i "s|registry=|registry=${REGISTRY_PATH}|g" .env
        sed -i "s/latest/${VERSION}/g" .env
        docker-compose build --build-arg APPERY_API_KEY=${APPERY_API_KEY}
        docker images

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push images to the Container registry
      working-directory: ./dev
      run: |
        pwd
        ls -la
        cat .env
        docker-compose push
