name: Deploy DEV CompreFace version

on: 
  push:
    branches:
      - master
      - 1.1.x

env:
  REGISTRY: ghcr.io
#  ENV_NAME: dev
  TAG     : master-fe21109
  REGISTRY_PATH: ghcr.io/exadel-inc/compreface/

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.sha_var.outputs.SHA_SHORT }}
      output2: ${{ steps.env_var.outputs.ENV_NAME }}

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3

    - id: sha_var
      run: echo "SHA_SHORT=$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_ENV
    - id: env_var
      run: |
        if [ "${{ github.ref_name }}" = "master" ]; then
          echo "ENV_NAME=dev" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" = "1.1.x" ]; then
          echo "ENV_NAME=stage" >> $GITHUB_ENV
        else
          echo "ENV_NAME=Features" >> $GITHUB_ENV
        fi 
  
  deploy:
    needs: job1
    runs-on: ${{needs.job1.outputs.output2}}

#    runs-on:
#      labels: $ENV_NAME

    steps:
#    - name: Checkout Repo 
#      uses: actions/checkout@v3

    - name: Deploy 
      working-directory: ./dev
      run: |
        sed -i "s|registry=|registry=${REGISTRY_PATH}|g" .env
        sed -i "s/latest/${TAG}/g" .env
        sudo docker-compose stop
        sudo docker system prune -a -f
        sudo docker-compose pull
        HOSTNAME=$HOSTNAME sudo docker-compose -f docker-compose.yml -f docker-compose.env.yml up -d
