name: Python package

on:
  push:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-python ]
  pull_request:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-python ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      working-directory: ./embedding-calculator/
      run: |
        python -m pip install --upgrade pip
        python -m pip install opencv-python
        python -m pip --no-cache-dir install -r requirements.txt
    - name: Test with pytest
      working-directory: ./embedding-calculator/src
      run: |
       pip install pytest
       pip install pytest-cov
       JOBLIB_MULTIPROCESSING=0 python -m pytest
