name: (Release) Build and Push Default CompreFace version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)arm3
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN_A }}
        password: ${{ secrets.DOCKER_HUB_PWD_A }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build images
      env:
        VERSION: ${{ github.event.inputs.version }}
        APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
      working-directory: ./dev/
      run: |
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        docker compose version
        docker-compose version
        docker compose build --help
        docker-compose build --help
        sed -i 's/registry=/registry=shutoffalexey\//g' .env
        docker-compose -f docker-compose.yml -f docker-compose.multiplatform.yml build --push --build-arg APPERY_API_KEY=${APPERY_API_KEY} compreface-admin
        sed -i 's/latest/${VERSION}/g' .env
        docker-compose -f docker-compose.yml -f docker-compose.multiplatform.yml build --push --build-arg APPERY_API_KEY=${APPERY_API_KEY} compreface-admin
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_LOGIN }}
    #     password: ${{ secrets.DOCKER_HUB_PWD }}
    # - name: Push images to Docker Hub
    #   working-directory: ./dev/
    #   env:
    #     VERSION: ${{ github.event.inputs.version }}
    #   run: |
    #     docker-compose push
    #     sed -i 's/${VERSION}/latest/g' .env
    #     docker-compose push

